version: "3.9"

services:
  redis:
    image: redis:7.0-alpine
    container_name: expenses-redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./.redis:/data

  postgres:
    image: postgres:14-alpine
    container_name: expenses-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expenses
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
